export default {
  login: 'BHUMESH438',
  id: 99005786,
  node_id: 'U_kgDOBea1Wg',
  avatar_url: 'https://avatars.githubusercontent.com/u/99005786?v=4',
  gravatar_id: '',
  url: 'https://api.github.com/users/BHUMESH438',
  html_url: 'https://github.com/BHUMESH438',
  followers_url: 'https://api.github.com/users/BHUMESH438/followers',
  following_url: 'https://api.github.com/users/BHUMESH438/following{/other_user}',
  gists_url: 'https://api.github.com/users/BHUMESH438/gists{/gist_id}',
  starred_url: 'https://api.github.com/users/BHUMESH438/starred{/owner}{/repo}',
  subscriptions_url: 'https://api.github.com/users/BHUMESH438/subscriptions',
  organizations_url: 'https://api.github.com/users/BHUMESH438/orgs',
  repos_url: 'https://api.github.com/users/BHUMESH438/repos',
  events_url: 'https://api.github.com/users/BHUMESH438/events{/privacy}',
  received_events_url: 'https://api.github.com/users/BHUMESH438/received_events',
  type: 'User',
  site_admin: false,
  name: 'Bhumesh',
  company: null,
  blog: '',
  location: 'Tamilnadu,India',
  email: null,
  hireable: true,
  bio: 'HI i like to code',
  twitter_username: null,
  public_repos: 38,
  public_gists: 1,
  followers: 11,
  following: 51,
  created_at: '2022-02-04T06:40:32Z',
  updated_at: '2023-09-05T07:21:10Z'
};
