export default [
  {
    login: 'gamemann',
    id: 6509565,
    node_id: 'MDQ6VXNlcjY1MDk1NjU=',
    avatar_url: 'https://avatars.githubusercontent.com/u/6509565?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/gamemann',
    html_url: 'https://github.com/gamemann',
    followers_url: 'https://api.github.com/users/gamemann/followers',
    following_url: 'https://api.github.com/users/gamemann/following{/other_user}',
    gists_url: 'https://api.github.com/users/gamemann/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/gamemann/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/gamemann/subscriptions',
    organizations_url: 'https://api.github.com/users/gamemann/orgs',
    repos_url: 'https://api.github.com/users/gamemann/repos',
    events_url: 'https://api.github.com/users/gamemann/events{/privacy}',
    received_events_url: 'https://api.github.com/users/gamemann/received_events',
    type: 'User',
    site_admin: false
  },
  {
    login: 'AYIDouble',
    id: 18186995,
    node_id: 'MDQ6VXNlcjE4MTg2OTk1',
    avatar_url: 'https://avatars.githubusercontent.com/u/18186995?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/AYIDouble',
    html_url: 'https://github.com/AYIDouble',
    followers_url: 'https://api.github.com/users/AYIDouble/followers',
    following_url: 'https://api.github.com/users/AYIDouble/following{/other_user}',
    gists_url: 'https://api.github.com/users/AYIDouble/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/AYIDouble/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/AYIDouble/subscriptions',
    organizations_url: 'https://api.github.com/users/AYIDouble/orgs',
    repos_url: 'https://api.github.com/users/AYIDouble/repos',
    events_url: 'https://api.github.com/users/AYIDouble/events{/privacy}',
    received_events_url: 'https://api.github.com/users/AYIDouble/received_events',
    type: 'User',
    site_admin: false
  },
  {
    login: 'H-K-R',
    id: 69351423,
    node_id: 'MDQ6VXNlcjY5MzUxNDIz',
    avatar_url: 'https://avatars.githubusercontent.com/u/69351423?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/H-K-R',
    html_url: 'https://github.com/H-K-R',
    followers_url: 'https://api.github.com/users/H-K-R/followers',
    following_url: 'https://api.github.com/users/H-K-R/following{/other_user}',
    gists_url: 'https://api.github.com/users/H-K-R/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/H-K-R/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/H-K-R/subscriptions',
    organizations_url: 'https://api.github.com/users/H-K-R/orgs',
    repos_url: 'https://api.github.com/users/H-K-R/repos',
    events_url: 'https://api.github.com/users/H-K-R/events{/privacy}',
    received_events_url: 'https://api.github.com/users/H-K-R/received_events',
    type: 'User',
    site_admin: false
  },
  {
    login: 'peter-kimanzi',
    id: 71552773,
    node_id: 'MDQ6VXNlcjcxNTUyNzcz',
    avatar_url: 'https://avatars.githubusercontent.com/u/71552773?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/peter-kimanzi',
    html_url: 'https://github.com/peter-kimanzi',
    followers_url: 'https://api.github.com/users/peter-kimanzi/followers',
    following_url: 'https://api.github.com/users/peter-kimanzi/following{/other_user}',
    gists_url: 'https://api.github.com/users/peter-kimanzi/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/peter-kimanzi/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/peter-kimanzi/subscriptions',
    organizations_url: 'https://api.github.com/users/peter-kimanzi/orgs',
    repos_url: 'https://api.github.com/users/peter-kimanzi/repos',
    events_url: 'https://api.github.com/users/peter-kimanzi/events{/privacy}',
    received_events_url: 'https://api.github.com/users/peter-kimanzi/received_events',
    type: 'User',
    site_admin: false
  },
  {
    login: 'Gizachew29',
    id: 72370435,
    node_id: 'MDQ6VXNlcjcyMzcwNDM1',
    avatar_url: 'https://avatars.githubusercontent.com/u/72370435?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/Gizachew29',
    html_url: 'https://github.com/Gizachew29',
    followers_url: 'https://api.github.com/users/Gizachew29/followers',
    following_url: 'https://api.github.com/users/Gizachew29/following{/other_user}',
    gists_url: 'https://api.github.com/users/Gizachew29/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/Gizachew29/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/Gizachew29/subscriptions',
    organizations_url: 'https://api.github.com/users/Gizachew29/orgs',
    repos_url: 'https://api.github.com/users/Gizachew29/repos',
    events_url: 'https://api.github.com/users/Gizachew29/events{/privacy}',
    received_events_url: 'https://api.github.com/users/Gizachew29/received_events',
    type: 'User',
    site_admin: false
  },
  {
    login: '0vm',
    id: 79897291,
    node_id: 'MDQ6VXNlcjc5ODk3Mjkx',
    avatar_url: 'https://avatars.githubusercontent.com/u/79897291?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/0vm',
    html_url: 'https://github.com/0vm',
    followers_url: 'https://api.github.com/users/0vm/followers',
    following_url: 'https://api.github.com/users/0vm/following{/other_user}',
    gists_url: 'https://api.github.com/users/0vm/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/0vm/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/0vm/subscriptions',
    organizations_url: 'https://api.github.com/users/0vm/orgs',
    repos_url: 'https://api.github.com/users/0vm/repos',
    events_url: 'https://api.github.com/users/0vm/events{/privacy}',
    received_events_url: 'https://api.github.com/users/0vm/received_events',
    type: 'User',
    site_admin: false
  },
  {
    login: 'Thuotracy',
    id: 80819977,
    node_id: 'MDQ6VXNlcjgwODE5OTc3',
    avatar_url: 'https://avatars.githubusercontent.com/u/80819977?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/Thuotracy',
    html_url: 'https://github.com/Thuotracy',
    followers_url: 'https://api.github.com/users/Thuotracy/followers',
    following_url: 'https://api.github.com/users/Thuotracy/following{/other_user}',
    gists_url: 'https://api.github.com/users/Thuotracy/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/Thuotracy/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/Thuotracy/subscriptions',
    organizations_url: 'https://api.github.com/users/Thuotracy/orgs',
    repos_url: 'https://api.github.com/users/Thuotracy/repos',
    events_url: 'https://api.github.com/users/Thuotracy/events{/privacy}',
    received_events_url: 'https://api.github.com/users/Thuotracy/received_events',
    type: 'User',
    site_admin: false
  },
  {
    login: 'gowthamselvaraj88',
    id: 119551097,
    node_id: 'U_kgDOByA0eQ',
    avatar_url: 'https://avatars.githubusercontent.com/u/119551097?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/gowthamselvaraj88',
    html_url: 'https://github.com/gowthamselvaraj88',
    followers_url: 'https://api.github.com/users/gowthamselvaraj88/followers',
    following_url: 'https://api.github.com/users/gowthamselvaraj88/following{/other_user}',
    gists_url: 'https://api.github.com/users/gowthamselvaraj88/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/gowthamselvaraj88/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/gowthamselvaraj88/subscriptions',
    organizations_url: 'https://api.github.com/users/gowthamselvaraj88/orgs',
    repos_url: 'https://api.github.com/users/gowthamselvaraj88/repos',
    events_url: 'https://api.github.com/users/gowthamselvaraj88/events{/privacy}',
    received_events_url: 'https://api.github.com/users/gowthamselvaraj88/received_events',
    type: 'User',
    site_admin: false
  },
  {
    login: 'D4Fi',
    id: 139288494,
    node_id: 'U_kgDOCE1frg',
    avatar_url: 'https://avatars.githubusercontent.com/u/139288494?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/D4Fi',
    html_url: 'https://github.com/D4Fi',
    followers_url: 'https://api.github.com/users/D4Fi/followers',
    following_url: 'https://api.github.com/users/D4Fi/following{/other_user}',
    gists_url: 'https://api.github.com/users/D4Fi/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/D4Fi/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/D4Fi/subscriptions',
    organizations_url: 'https://api.github.com/users/D4Fi/orgs',
    repos_url: 'https://api.github.com/users/D4Fi/repos',
    events_url: 'https://api.github.com/users/D4Fi/events{/privacy}',
    received_events_url: 'https://api.github.com/users/D4Fi/received_events',
    type: 'User',
    site_admin: false
  },
  {
    login: 'alternbit',
    id: 142718182,
    node_id: 'U_kgDOCIG05g',
    avatar_url: 'https://avatars.githubusercontent.com/u/142718182?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/alternbit',
    html_url: 'https://github.com/alternbit',
    followers_url: 'https://api.github.com/users/alternbit/followers',
    following_url: 'https://api.github.com/users/alternbit/following{/other_user}',
    gists_url: 'https://api.github.com/users/alternbit/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/alternbit/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/alternbit/subscriptions',
    organizations_url: 'https://api.github.com/users/alternbit/orgs',
    repos_url: 'https://api.github.com/users/alternbit/repos',
    events_url: 'https://api.github.com/users/alternbit/events{/privacy}',
    received_events_url: 'https://api.github.com/users/alternbit/received_events',
    type: 'User',
    site_admin: false
  },
  {
    login: 'mahseema',
    id: 143227828,
    node_id: 'U_kgDOCIl7tA',
    avatar_url: 'https://avatars.githubusercontent.com/u/143227828?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/mahseema',
    html_url: 'https://github.com/mahseema',
    followers_url: 'https://api.github.com/users/mahseema/followers',
    following_url: 'https://api.github.com/users/mahseema/following{/other_user}',
    gists_url: 'https://api.github.com/users/mahseema/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/mahseema/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/mahseema/subscriptions',
    organizations_url: 'https://api.github.com/users/mahseema/orgs',
    repos_url: 'https://api.github.com/users/mahseema/repos',
    events_url: 'https://api.github.com/users/mahseema/events{/privacy}',
    received_events_url: 'https://api.github.com/users/mahseema/received_events',
    type: 'User',
    site_admin: false
  }
];
